[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm --prefix frontend install",
  "npm --prefix server install"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build"
]

[start]
cmd = "npm --prefix server start"
